apiVersion: klot.io/v1
kind: App
metadata:
  name: chore-google.nandy.io
  description: Chore Google - Nandy I/O
spec:
  source:
    site: github.com
    repo: nandy-io/chore-google-daemon
  manifests:
  - path: kubernetes/namespace.yaml
  - path: kubernetes/daemon.yaml
  requires:
  - site: github.com
    repo: nandy-io/chore
