apiVersion: klot.io/v1
kind: App
metadata:
  name: chore-google.nandy.io
  version: v0.1
  description: Chore Google - Nandy I/O
spec:
  namespace: chore-google-nandy-io
  manifests:
  - path: kubernetes/namespace.yaml
  - path: daemon/kubernetes/daemon.yaml
  requires:
  - name: redis.klot.io
    source:
      site: github.com
      repo: klot-io/redis
  - name: chore.nandy.io
    source:
      site: github.com
      repo: nandy-io/chore
